# Site settings
title: Eletrônica Industrial
email: dimasad@ufmg.br
description: "Material auxiliar da disciplina EMA248 da UFMG"
baseurl: "/ema248"
url: "http://dimasad.github.io"
show_downloads: false
google_analytics: false
theme: jekyll-theme-slate

# Build settings
markdown: kramdown
permalink: pretty
kramdown:
  syntax_highlighter_opts:
    default_lang: c++
